name: github-repo-stats

on:
    schedule:
        - cron: "0 11 * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    collect-stats:
        name: collect-repo-stats
        if: github.repository == 'awslabs/sample-FAST-applications'
        runs-on: ubuntu-latest
        steps:
            - name: run-ghrs
              uses: jgehrcke/github-repo-stats@d80572c9029636cd0e97e3a79e7a9c293bea3b02 # RELEASE
              with:
                  ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
                  ghpagesprefix: "https://awslabs.github.io/sample-FAST-applications"
